url: https://datasart.github.io
baseurl: https://datasart.github.io

# Site settings
title: DataSart
email: datasart@domain.com
description: "A Machine Learning Based Startup"


# Team names, titles and social links
people:
- name: Vu Anh Duc
  pic: 2
  position: CEO
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    #- title: facebook
      #url: #
    - title: linkedin
      url: https://vn.linkedin.com/in/ducva
- name: Mai Xuan Trang
  pic: 1
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    #- title: facebook
     # url: #
    - title: linkedin
      url: https://vn.linkedin.com/in/trangmx
- name: Nguyen Hung Cuong
  pic: 3
  position: CTO
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    - title: facebook
      url: https://www.facebook.com/nhcuong269
    #- title: google-plus
      #url: #

- name: Trinh Quyet Thang
  pic: 4
  position: Junior Leader
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    - title: facebook
      url: https://www.facebook.com/love.to.be.love.by.sn
    #- title: google-plus
      #url: #
- name: Nguyen Tu Lam
  pic: Tu
  position: COO
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    - title: facebook
      url: https://www.facebook.com/tu.lam.3
    #- title: google-plus
      #url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/DataSart
  #- title: facebook
    #url:
  #- title: stack-overflow
    #url:
  #- title: bitbucket
    #url:
  - title: github
    url: https://github.com/datasart

# Postal address (add as many lines as necessary)
address:
  - line: Trung Hoa, Nhan Chinh
  - line: Ha Noi, Viet Nam

# Build settings
markdown: kramdown
permalink: pretty
