url: https://datasart.github.io
baseurl: https://datasart.github.io

# Site settings
title: DataSart
email: datasart@domain.com
description: "A Machine Learning Based Startup"


# Team names, titles and social links
people:
- name: Mai Xuan Trang
  pic: trang
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Vu Anh Duc
  pic: duc
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Nguyen Hung Cuong
  pic: cuong
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/DataSart
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/DataSart
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/datasart

# Postal address (add as many lines as necessary)
address:
  - line: Trung Hoa, Nhan Chinh
  - line: Ha Noi, Viet Nam

# Build settings
markdown: kramdown
permalink: pretty